In [1]:
import pickle
with open('knn_model.pickle','rb') as f:
  knn_new = pickle.load(f)

In [3]:
with open('scaler.pickle','rb') as f:
  scaler_new = pickle.load(f)

In [4]:
import pandas as pd
new_df = pd.read_csv("https://raw.githubusercontent.com/futurexskill/projects/main/knn-classification/new_customers.csv")

In [5]:
new_df

Gender  Age  Salary  Product ID  Price
0    Male   24   38652           3   4446
1  Female   47   64727           1   5188
2    Male   46   54648           1   6193
3    Male   31   20018           3   4779
4    Male   58   77731           2   6855
5    Male   28   55478           1   6153
6  Female   48   54211           2   7588
7    Male   31   60076           3   5238
8  Female   42   29290           1   5418
9    Male   50   21445           1   5598

In [6]:
len(new_df)

10

In [7]:
gender_encoded_new = pd.get_dummies(new_df['Gender'], drop_first=True)

In [8]:
gender_encoded_new

Male
0     1
1     0
2     1
3     1
4     1
5     1
6     0
7     1
8     0
9     1

In [9]:
df_new_2 = pd.concat([new_df,gender_encoded_new],axis=1)

In [10]:
df_new_2

Gender  Age  Salary  Product ID  Price  Male
0    Male   24   38652           3   4446     1
1  Female   47   64727           1   5188     0
2    Male   46   54648           1   6193     1
3    Male   31   20018           3   4779     1
4    Male   58   77731           2   6855     1
5    Male   28   55478           1   6153     1
6  Female   48   54211           2   7588     0
7    Male   31   60076           3   5238     1
8  Female   42   29290           1   5418     0
9    Male   50   21445           1   5598     1

In [11]:
x_new = df_new_2[['Male','Age','Salary','Price']].to_numpy()

In [12]:
x_new

array([[    1,    24, 38652,  4446],
       [    0,    47, 64727,  5188],
       [    1,    46, 54648,  6193],
       [    1,    31, 20018,  4779],
       [    1,    58, 77731,  6855],
       [    1,    28, 55478,  6153],
       [    0,    48, 54211,  7588],
       [    1,    31, 60076,  5238],
       [    0,    42, 29290,  5418],
       [    1,    50, 21445,  5598]])

In [13]:
x_new_scale2 = scaler_new.fit_transform(x_new)

In [14]:
x_new_scale2

array([[ 0.65465367, -1.54774434, -0.48875298, -1.42543997],
       [-1.52752523,  0.60971747,  0.93112246, -0.61159228],
       [ 0.65465367,  0.51591478,  0.38228547,  0.49072164],
       [ 0.65465367, -0.89112553, -1.50343981, -1.06019565],
       [ 0.65465367,  1.64154703,  1.63923599,  1.21682294],
       [ 0.65465367, -1.17253359,  0.42748189,  0.44684845],
       [-1.52752523,  0.70352015,  0.35848928,  2.02079916],
       [ 0.65465367, -0.89112553,  0.67785916, -0.55675079],
       [-1.52752523,  0.14070403, -0.99854681, -0.35932143],
       [ 0.65465367,  0.89112553, -1.42573465, -0.16189207]])

In [15]:
y_new_pred = knn_new.predict(x_new_scale2)

In [16]:
y_new_pred

array([0, 1, 1, 0, 0, 1, 0, 0, 0, 0])

In [17]:
df_new_2['will_purchase'] = y_new_pred

In [18]:
df_new_2

Gender  Age  Salary  Product ID  Price  Male  will_purchase
0    Male   24   38652           3   4446     1              0
1  Female   47   64727           1   5188     0              1
2    Male   46   54648           1   6193     1              1
3    Male   31   20018           3   4779     1              0
4    Male   58   77731           2   6855     1              0
5    Male   28   55478           1   6153     1              1
6  Female   48   54211           2   7588     0              0
7    Male   31   60076           3   5238     1              0
8  Female   42   29290           1   5418     0              0
9    Male   50   21445           1   5598     1              0

In [19]:
df_new_2.to_csv("model_predictions.csv",index=False)

In [20]:
# predict for 1 row
row_values = [1, 32, 40000,5000]


In [21]:
# reshape it to a 2D NumPy array
import numpy as np
x_new = np.array(row_values).reshape(1,-1)
x_new

array([[    1,    32, 40000,  5000]])

In [22]:
x_new_scale2 = scaler_new.fit_transform(x_new)

In [23]:
x_new_scale2

array([[0., 0., 0., 0.]])

In [24]:
y_new_pred = knn_new.predict(x_new_scale2)

In [25]:
prediction =str(y_new_pred[0])


In [26]:
print("Purchase ? "+str(prediction))


Purchase ? 0
